version: "3.7"
services:
    api:
        image: vikasl/libraryapi
        depends_on: 
            - sql
        ports:
            - 80:80
        environment: 
            - ConnectionStrings__LibraryDatabase=server=sql;database=library;user=sa;password=TokyoJoe138!
        networks:
            - my-network
    sql:
        image: vikasl/librarysql
        ports:
            - 1433:1433
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
